name: Deployment

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: Deployment environment
        default: dev
        type: choice
        options:
          - dev
          - live
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.ENV }}
    steps:
      - run: echo "Run"
