name: Deployment

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: Deployment environment
        default: dev
        type: choice
        options:
          - dev
          - qa
          - live
jobs:
  set-env:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.ENV }}
    steps:
      - run: echo "Set env"
  build:
    needs: set-env
    runs-on: ubuntu-latest
    steps:
      - run: echo "${env.CLUSTER}"
  